spring:
  application:
    name: ms-lista-espera

  datasource:
    url: jdbc:mysql://localhost:3306/db_lista_espera
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${IDP_JWKS_URI:http://localhost:9000/.well-known/jwks.json%7D

server:
  port: 8085

